MyAutoService/Models/ServiceType.cs
using System.ComponentModel.DataAnnotations;

namespace MyAutoService.Models
{
	public class ServiceType
	{
        public int Id { get; set; }


		[Display(Name= " Name :")]
		[Required(ErrorMessage ="Please Add Your Name")]
		[MaxLength(555)]
		public string Name { get; set; }

		[Display(Name = "Price : ")]
		[Required(ErrorMessage = "Please Add Your Price")]
        public double Price { get; set; }
    }
}

MyAutoService/Pages/Cars/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyAutoService.Data;
using MyAutoService.Models;

namespace MyAutoService.Pages.Cars
{
    public class CreateModel : PageModel
    {
        private readonly MyAutoService.Data.ApplicationDbContext _context;

        public CreateModel(MyAutoService.Data.ApplicationDbContext context)
        {
            _context = context;
        }

		[BindProperty]
		public Car Car { get; set; }

		public IActionResult OnGet(string userId = null)
        {
            Car = new Car();
            if (userId == null)
            {
                var ClaimIdentity = (ClaimsIdentity)User.Identity;
                var Claim = ClaimIdentity.FindFirst(ClaimTypes.NameIdentifier);
                userId = Claim.Value;
            }

            Car.UserId = userId;

            return Page();
        }

        [BindProperty]
        public IFormFile ImgUp { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
			if (ImgUp != null)
			{
				Car.ImageName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
				string savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/CarImages", Car.ImageName);
				using (var fileStream = new FileStream(savePath, FileMode.Create))
				{
					ImgUp.CopyTo(fileStream);
				}
			}
			_context.Cars.Add(Car);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

MyAutoService/Pages/ServiceTypes/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyAutoService.Data;
using MyAutoService.Models;
using MyAutoService.Utilities;

namespace MyAutoService.Pages.ServiceTypes
{
	[Authorize(Roles = SD.AdminEndUser)]
	public class CreateModel : PageModel
    {
        ApplicationDbContext _db;
        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public ServiceType ServiceType { get; set; }
        public IActionResult OnGet()
        {
            return Page();
        }

		public async Task<IActionResult> OnPost(ServiceType serviceType)
		{
			if (!ModelState.IsValid)
			{
				return Page();

			}

			_db.ServiceTypes.Add(serviceType);
			await _db.SaveChangesAsync();
			return RedirectToPage("Index");
		}
		//      public IActionResult OnPost(ServiceType serviceType)
		//      {
		//          if(!ModelState.IsValid)
		//          {
		//		return Page();

		//          }

		//         _db.ServiceTypes.Add(serviceType);
		//          _db.SaveChanges();
		//	return RedirectToPage("Index");
		//}
	}
}

MyAutoService/Pages/ServiceTypes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Models;
using MyAutoService.Utilities;

namespace MyAutoService.Pages.ServiceTypes
{
	[Authorize(Roles = SD.AdminEndUser)]
	public class DetailsModel : PageModel
    {
        private readonly MyAutoService.Data.ApplicationDbContext _context;

        public DetailsModel(MyAutoService.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public ServiceType ServiceType { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ServiceType = await _context.ServiceTypes.FirstOrDefaultAsync(m => m.Id == id);

            if (ServiceType == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

MyAutoService/Pages/Services/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Models;
using MyAutoService.Models.ViewModels;

namespace MyAutoService.Pages.Services
{
	[Authorize]
	public class CreateModel : PageModel
	{
		private ApplicationDbContext _db;
		public CreateModel(ApplicationDbContext db)
		{
			_db = db;
		}
		[BindProperty]
		public CarServiceviewModel CarServiceVM { get; set; }
		public async Task<IActionResult> OnGet(int carId)
		{
			CarServiceVM = new CarServiceviewModel()
			{
				car = await _db.Cars.Include(c => c.ApplicationUser)
				.FirstOrDefaultAsync(c => c.Id == carId),
				ServiceHeader = new ServiceHeader()

			};
			List<string> lstServiceTypeInShoppingCart = _db.ServicesShoppingCarts
				.Include(c => c.ServiceType)
				.Where(c => c.CarId == carId)
				.Select(c => c.ServiceType.Name)
				.ToList();

			IQueryable<ServiceType> lstServices = from s in _db.ServiceTypes
												  where !(lstServiceTypeInShoppingCart.Contains(s.Name))
												  select s;

			CarServiceVM.ServiceTypesList = lstServices.ToList();
			CarServiceVM.ServicesShoppingCart = _db.ServicesShoppingCarts.Include(c => c.ServiceType)
				.Where(c => c.CarId == carId)
				.ToList();
			CarServiceVM.ServiceHeader.TotalPrice = 0;
			foreach (var item in CarServiceVM.ServicesShoppingCart)
			{
				CarServiceVM.ServiceHeader.TotalPrice = item.ServiceType.Price;
			}
			return Page();
		}


		public async Task<IActionResult> OnPost()
		{
			if(ModelState.IsValid)
			{
				CarServiceVM.ServiceHeader.Dateadded = DateTime.Now;
				CarServiceVM.ServicesShoppingCart = _db.ServicesShoppingCarts.Include(c => c.ServiceType)
					.Where(c => c.CarId == CarServiceVM.car.Id) .ToList();
				foreach (var shop in CarServiceVM.ServicesShoppingCart)
				{
					CarServiceVM.ServiceHeader.TotalPrice += shop.ServiceType.Price;
				}
				CarServiceVM.ServiceHeader.CarId = CarServiceVM.car.Id;
				_db.ServiceHeaders.Add(CarServiceVM.ServiceHeader);
				await _db.SaveChangesAsync();

				foreach (var shop in CarServiceVM.ServicesShoppingCart)
				{
					ServiceDetails details = new ServiceDetails()
					{
						ServiceHeaderId = CarServiceVM.ServiceHeader.Id,
						ServiceName = shop.ServiceType.Name,
						ServicePrice = shop.ServiceType.Price,
						ServiceTypeId = shop.ServiceTypeId
					};
					_db.ServiceDetails.Add(details);
				}
				_db.ServicesShoppingCarts.RemoveRange(CarServiceVM.ServicesShoppingCart);
				await _db.SaveChangesAsync();
				return RedirectToPage("/Cars/Index", new { userId = CarServiceVM.car.UserId });
			}
			return Page();
		}

		public async Task<IActionResult> OnPostAddToCart()
		{
			ServicesShoppingCart shopping = new ServicesShoppingCart()
			{
				CarId = CarServiceVM.car.Id,
				ServiceTypeId = CarServiceVM.ServiceDetails.ServiceTypeId
			};
			_db.ServicesShoppingCarts.Add(shopping);
			await _db.SaveChangesAsync();
			return RedirectToPage("Create", new {carId = CarServiceVM.car.Id});
		}
		public async Task<IActionResult> OnPostRemoveFromCart(int serviceTypeId)
		{
			ServicesShoppingCart shopping = _db.ServicesShoppingCarts
				.First(u => u.CarId == CarServiceVM.car.Id && u.ServiceTypeId == serviceTypeId);
			_db.Remove(shopping);
			await _db.SaveChangesAsync();
			return RedirectToPage("Create", new { carId = CarServiceVM.car.Id });
		}
	}
}

MyAutoService/Pages/Services/Details.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Models;

namespace MyAutoService.Pages.Services
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private ApplicationDbContext _context;
        public DetailsModel(ApplicationDbContext context)
        {
			_context = context;

		}
        [BindProperty]
        public ServiceHeader ServiceHeader { get; set; }
        public List<ServiceDetails> ServiceDetails { get; set; }
        public IActionResult OnGet(int serviceid)
        {
            ServiceHeader = _context.ServiceHeaders
                .Include(s => s.Car)
                .Include(s => s.Car.ApplicationUser)
                .FirstOrDefault(s => s.Id == serviceid);


            if (ServiceHeader == null)
            
                return NotFound();

                ServiceDetails = _context.ServiceDetails.Where(d => d.ServiceHeaderId == serviceid).ToList();

                return Page();

            
        }
    }
}

MyAutoService/Pages/Services/History.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Models;

namespace MyAutoService.Pages.Services
{
	[Authorize]
	public class HistoryModel : PageModel
	{
		private ApplicationDbContext _context;
		public HistoryModel(ApplicationDbContext context)
		{
			_context = context;
		}

        [BindProperty]
        public List<ServiceHeader> ServiceHeaders { get; set; }

        public string UserId { get; set; }

        public void OnGet(int carId)
		{
            ServiceHeaders = _context.ServiceHeaders
                .Include(c => c.Car)
                .Include(c => c.Car.ApplicationUser)
                .Where(c => c.CarId == carId).ToList();

            UserId = _context.Cars.Where(c => c.Id == carId).FirstOrDefault().UserId;
        }
	}
}

MyAutoService/Pages/Services/Create.cshtml
@page
@model MyAutoService.Pages.Services.CreateModel
@{
	ViewData["Title"] = "New SerVice";
}
<div class="container pt-4 pb-2 row">
	<div class="col-6"></div>
	<h2 class=" text-info py-2">Add New Service</h2>
	<div class="col-6 ">
		<a asp-asp-page="/Cars/Index" asp-asp-route-userId="@Model.CarServiceVM.car.UserId" class="btn btn-outline-success form-control"> Bacck To List</a>
	</div>

</div>

<div class="container">
	<div class="card">
		<div class="card-header bg-dark text-light  ml-0 row container"></div>
		<div class="col-1 text-center pt-3 text-white-50">
			<i class="fas fa-user fa-2x"></i>
			<div class="col-5">
				<label class="text-info">
					@Model.CarServiceVM.car.ApplicationUser.Name
				</label><br />
				<label class="text-info">
					@Model.CarServiceVM.car.ApplicationUser.Email
				</label>
			</div>
			<div class="col-1 text-center pt-3 text-white-50">
				<i class="fas fa-car fa-2x"></i>
			</div>
			<div class="col-5">
				<label class="text-info">
					@Model.CarServiceVM.car.Name @Model.CarServiceVM.car.Model
				</label><br />
				<label class="text-info">
					@Model.CarServiceVM.car.Year  @Model.CarServiceVM.car.Color
				</label>
			</div>

		</div>
	</div>
	<div class="card-body">
		<from method="post" style="width : 100%">
			<div class=" container">
				<input hidden asp-for="CarServiceVM.car.Model" />
				<input hidden asp-for="CarServiceVM.car.Id" />
				<input hidden asp-for="CarServiceVM.car.UserId" />
				<input hidden asp-for="CarServiceVM.car.Name" />
				<input hidden asp-for="CarServiceVM.car.Year" />
				<div class="border rounded p-2">
					<div class="row">
						<div class="col-3">
							<h2 class="text-info" pl-3 p2-2 pb-1>New Servic</h2>

						</div>
						<div class="col-9 pb-1 pt-2"></div>
						<div class="row">
							<div class="col-8">
								<select asp-for="CarServiceVM.ServiceDetails.ServiceTypeId"
										action="form-control"
										asp-items="@(new SelectList(Model.CarServiceVM.ServiceTypesList ,"Id","Name" ))"></select>
							</div>
							<div class="col-4">
								<input type="submit" asp-asp-page-handler="AddToCart" class="form-control btn btn-primary" value="Add" />
							</div>
						</div>
					</div>

				</div>
				<div class="border container rounded p-2"></div>
				<h3 class="text-info pb-2"> services INformation</h3>
				@if (Model.CarServiceVM.ServicesShoppingCart.Count == 1)
				{
					<p>No Service Exit</p>
				}
				else
				{

				}
				<div class="row mt-3">
					<div class="col-7">
						<table class="table table-striped border">
							<tr class="table-secondary">
								<th>@Html.DisplayNameFor(m =>Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Name)</th>
								<th>@Html.DisplayNameFor(m =>Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Price)</th>
								<th></th>

							</tr>
							@foreach (var item in Model.CarServiceVM.ServicesShoppingCart)
							{
								<tr>
									<td>
										@item.ServiceType.Name
									</td>
									<td>
										@item.ServiceType.Price
									</td>
									<td>
										<button type="submit" asp-asp-page-handler="RemoveFromCart"
										asp-route-serviceTypeId ="@item.ServiceTypeId"
										class="btn btn-danger form-control ">
									<i class="fas fa-trash"></i>
									</button>
									</td>
								</tr>
							}
							<tr style="background-color : #e2fee2">
								<td colspan="1" class="text-success">
									Sum All
								</td>
								<td colspan="2">
									@Model.CarServiceVM.ServiceHeader.TotalPrice.ToString();
								</td>
							</tr>
						</table>
					</div>
					<div class="col-5 px-4 pb-2">
						<div class="row ">
							<div class="col-3 p-0">
								<label asp-for="CarServiceVM.ServiceHeader.Miles"
								class="form-control" style="border : none "></label>
							</div>
							<div class="col-9">
								<input asp-for="CarServiceVM.ServiceHeader.Miles"
								class="form-control" id=" txtMiles"/>
							</div>
						</div>

						<div class="row  py-2">
							<div class="col-3">
							
							</div>
							<div class="col-12">
								<textarea placeholder="	Description" asp-for="CarServiceVM.ServiceHeader.Description"
								class="form-control" style="height : 100px "></textarea>
							</div>
						</div>
						<div class="row">
							<div class="col-12">
								<button type="submit" onclick="return validateInput()" class="btn btn-success form-control">
									submit Service
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</from>
	</div>
</div>

@section Scripts
{
	<partial name="_ValidationScriptsPartial"/>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script>
		function validateInput() {
			var miles = document.getElementById("txtMiles").value;
			if (miles < 1) {
				
				swal("Error ! ", InserT Kilometer, "error");
				return false;
			}
		}
	</script>

	
}

MyAutoService/Pages/Services/Details.cshtml
@page
@model MyAutoService.Pages.Services.DetailsModel
@{
}
<div class="container pt-4 row border">
	<div class="col-6">
		<h2 class="text-info py-2 ">Detaills Service </h2>

	</div>
	<div class="col-3 offset-3 text-right py-2">
		<a asp-page="/Services/History" asp-route-carId="@Model.ServiceHeader.CarId" class="btn btn-outline-success form-control">
			back To List
		</a>
	</div>
</div>
<div class="container pt-5">
	<div class="card">
		<div class=" card-header bg-dark text-light ml-0 row container">
			<div class="col-1 text-center pt-3 text-white-50">
				<i class="fas fa-user"></i>
			</div>
			<div class="col-5">
				<label class="text-info">
					@Model.ServiceHeader.Car.ApplicationUser.Name
				</label>
				<br />
				<label class="text-info">
					@Model.ServiceHeader.Car.ApplicationUser.Email / @Model.ServiceHeader.Car.ApplicationUser.PhoneNumber
				</label>

			</div>
			<div class="col-5">
				<label class="text-info">
					@Model.ServiceHeader.Car.Model /@Model.ServiceHeader.Car.Color
				</label>
				<br />
				<label class="text-info">
					@Model.ServiceHeader.Car.Name
				</label>
			</div>
			<div>
				class="col-1 text-center pt-3 text-white-50">
				<i class="fas fa-car"></i>
			</div>
		</div>
	</div>
	<div class="card-body">
		<div class="row pt-3">
			<div class="col-5 px-4 pb-2"></div>
			<div class=" row">
				<div class="col-3">
					<label asp-for="ServiceHeader.Miles" class="form-control" style="border : none"></label>

				</div>
				<div class="col-9">
					<input asp-for="ServiceHeader.Miles" readonly class="form-control" />
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<textarea asp-for="ServiceHeader.Description" readonly class="form-control"></textarea>
				</div>
			</div>
			<table class="table table-striped border">
				<tr class="table-secondary">
					<th>
						@Html.DisplayNameFor(m => m.ServiceDetails[0].ServiceName)
					</th>
					<th>
						@Html.DisplayNameFor(m => m.ServiceDetails[0].ServicePrice)
					</th>


				</tr>
				@foreach (var item in Model.ServiceDetails)
				{
					<tr>
						<td>
							@item.ServiceName
						</td>
						<td>
							@item.ServicePrice.ToString("#,Euro")
						</td>

						<td>
							<a asp-page="Details" class="btn btn-info form-control"
							   asp-route-serviceid="@item.Id">
								Description
							</a>
						</td>

					</tr>

				}
			</table>
		</div>
	</div>
</div>

MyAutoService/Pages/Services/History.cshtml
@page
@model MyAutoService.Pages.Services.HistoryModel
@{
}

<div class="container pt-4 row border">
	<div class="col-6">
		<h2 class="text-info py-2 ">History Service </h2>

	</div>
	<div class="col-3 offset-3 text-right py-2">
		<a asp-page="/Cars/Index" asp-route-userId="@Model.UserId" class="btn btn-outline-success form-control">
			بازگشت به لیست
		</a>
	</div>
</div>

@if (Model.ServiceHeaders.Count == 0)
{
	<div class="alert aler-info">
		Thereis no history
	</div>
}
else
{
	<div class="container pt-5">
		<div class="card">
			<div class=" card-header bg-dark text-light ml-0 row container">
				<div class="col-1 text-center pt-3 text-white-50">
					<i class="fas fa-user"></i>
				</div>
				<div class="col-5">
					<label class="text-info">
						@Model.ServiceHeaders[0].Car.ApplicationUser.Name
					</label>
					<br />
					<label class="text-info">
						@Model.ServiceHeaders[0].Car.ApplicationUser.Email / @Model.ServiceHeaders[0].Car.ApplicationUser.PhoneNumber
					</label>

				</div>
				<div class="col-5">
					<label class="text-info">
						@Model.ServiceHeaders[0].Car.Model /@Model.ServiceHeaders[0].Car.Color
					</label>
					<br />
					<label class="text-info">
						@Model.ServiceHeaders[0].Car.Name
						</label>
				</div>
				<div>
					class="col-1 text-center pt-3 text-white-50">
					<i class="fas fa-car"></i>
				</div>
			</div>
		</div>
		<div class="card-body">
			<table class="table table-striped border">
				<tr class="table-secondary">
					<th>
						@Html.DisplayNameFor(m => m.ServiceHeaders[0].Miles)
					</th>
					<th>
						@Html.DisplayNameFor(m => m.ServiceHeaders[0].TotalPrice)
					</th>
					<th>
						@Html.DisplayNameFor(m => m.ServiceHeaders[0].Description)
					</th>
					<th>
						@Html.DisplayNameFor(m => m.ServiceHeaders[0].Dateadded)
					</th>
					<th></th>
				</tr>
				@foreach (var item in Model.ServiceHeaders)
				{
					<tr>
						<td>
							@item.Miles
						</td>
						<td>
							@item.TotalPrice.ToString("#,Euro")
						</td>
						<td>
							@item.Description
						</td>
						<td>
							@item.Dateadded
						</td>
						<td>
							<a asp-page="Details" class="btn btn-info form-control"
							   asp-route-serviceid="@item.Id">
								Description
							</a>
						</td>

					</tr>

				}
			</table>
		</div>
	</div>
}